defaults:
  - _self_
  - augmentations: symmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "simclr-res"
method: "simclr"
backbone:
  name: "resnet18"
# backbone:
#   name: "vit_tiny"
#   kwargs:
#     patch_size: 16
#     img_size: 256

method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 384
  temperature: 0.5
data:
  dataset: custom
  train_path: "/data/datasets/camelyon16/train"
  no_labels: True
  val_path: ""
  format: "dali"
  # image_folder
  num_workers: 5
optimizer:
  name: "lars"
  batch_size: 320
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1e-5
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True
  max_hours: 300

max_epochs: 200
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
